api_platform:
    collection:
        pagination:
            items_per_page: 500
    mapping:
        paths: [ '%kernel.project_dir%/src/Entity' ]
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
    formats:
        json: [ 'application/json' ]
        xml: [ 'application/xml', 'text/xml' ]
        yaml: [ 'application/x-yaml' ]
        csv: [ 'text/csv' ]
        html: [ 'text/html' ]
        myformat: [ 'application/vnd.myformat' ]
