doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        charset: UTF8

        host:     '%env(resolve:DATABASE_HOST)%'
        port:     '%env(resolve:DATABASE_PORT)%'
        dbname:   '%env(resolve:DATABASE_DBNAME)%'
        user:     '%env(resolve:DATABASE_USER)%'
        password: '%env(resolve:DATABASE_PASSWORD)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
